name: Workflow Y
on:
  workflow_dispatch:

jobs:
  y-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: List files in repository
        run: ls -la
      - name: git branch list
        run: git branch -l
